#
# https://rust-lang.github.io/rustfmt
#
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
wrap_comments = true
